AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Deep Security Provider
Parameters:
  LambdaS3Bucket:
    Type: String
    Default: ''
  CFNCustomProviderZipFileName:
    Type: String
    Default: lambdas/cfn-deep-security-provider-0.3.0.zip
Conditions:
  UsePublicBucket: !Equals
    - !Ref 'LambdaS3Bucket'
    - ''
Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties:
      PolicyName: CFNCustomDeepSecurityProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cfn-deep-security-provider/*'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/datadog/*'
      Roles:
        - !Ref 'LambdaRole'
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  CFNDeepSecurityProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
    Properties:
      Description: CloudFormation Deep Security Provider
      Code:
        S3Bucket: !If
          - UsePublicBucket
          - !Sub 'binxio-public-${AWS::Region}'
          - !Ref 'LambdaS3Bucket'
        S3Key: !Ref 'CFNCustomProviderZipFileName'
      FunctionName: cfn-deep-security-provider
      Handler: provider.handler
      Timeout: 600
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.9

  DatadogEventForwarder:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
    Properties:
      Description: DeepSecurity -> DataDog SNS event forwarder
      Code:
        S3Bucket: !If
          - UsePublicBucket
          - !Sub 'binxio-public-${AWS::Region}'
          - !Ref 'LambdaS3Bucket'
        S3Key: !Ref 'CFNCustomProviderZipFileName'
      FunctionName: deep-security-datadog-event-forwarder
      Handler: datadog_event_forwarder.handler
      Timeout: 600
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.7
      Environment:
        Variables:
          DATADOG_API_KEY: ssm:///datadog/api-key
          DATADOG_TAGS: tag1=value1, tag2=value2

