AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Deep Security Provider
Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNCustomDeepSecurityProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cfn-deep-security-provider/*'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/datadog/*'
      Roles:
        - !Ref 'LambdaRole'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  CFNDeepSecurityProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaPolicy
    Properties:
      Description: CloudFormation Deep Security Provider
      PackageType: Image
      Code:
        ImageUri: 463637877380.dkr.ecr.eu-central-1.amazonaws.com/xebia/cfn-deep-security-provider:1.0.1
      FunctionName: cfn-deep-security-provider
      Timeout: 600
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'

  DatadogEventForwarder:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaPolicy
    Properties:
      Description: DeepSecurity -> DataDog SNS event forwarder
      PackageType: Image
      Code:
        ImageUri: 463637877380.dkr.ecr.eu-central-1.amazonaws.com/xebia/cfn-deep-security-provider:1.0.1
      FunctionName: deep-security-datadog-event-forwarder
      Timeout: 600
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Environment:
        Variables:
          HANDLER: datadog-event-forwarder
          DATADOG_API_KEY: ssm:///datadog/api-key
          DATADOG_TAGS: tag1=value1, tag2=value2

