AWSTemplateFormatVersion: '2010-09-09'
Description: Deep Security Demo Configuration
Resources:
  Context:
    Type: Custom::DeepSecurityContext
    Properties:
      Value:
        name: My Context
        description: Context
        minimumAgentVersion: 6.0.0.0
        localConnectionsEnabled: True
        remoteConnectionsEnabled: False
        noConnectionEnabled: False
        noInternetEnabled: False
        restrictedInterfacesEnabled: True
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-deep-security-provider'

  Policy:
    Type: Custom::DeepSecurityPolicy
    Properties:
      Value:
        name: My Policy
        firewall:
          state: 'on'
          ruleIDs:
            - '{{lookup "firewallRule" "FTP Server"}}'
            - '{{lookup "firewallRule" "SMTP Server"}}'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-deep-security-provider'
